# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x0e\x65xamplePackage\x1a\x1bgoogle/protobuf/empty.proto\"(\n\x0c\x64\x61taResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\'\n\x0b\x64\x61taRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t2\x91\x01\n\x07\x45xample\x12\x41\n\x07getData\x12\x16.google.protobuf.Empty\x1a\x1c.examplePackage.dataResponse\"\x00\x12\x43\n\ncreateData\x12\x1b.examplePackage.dataRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATARESPONSE._serialized_start=62
  _DATARESPONSE._serialized_end=102
  _DATAREQUEST._serialized_start=104
  _DATAREQUEST._serialized_end=143
  _EXAMPLE._serialized_start=146
  _EXAMPLE._serialized_end=291
# @@protoc_insertion_point(module_scope)
