name: Build Package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing Packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv requirements > requirements.txt
        pip install -r requirements.txt
    - name: Building pb2 packages
      env:
        PACKAGE_NAME: ${{ github.event.repository.name }}
      run: . ./scripts/build.sh
    - name: Building wheel package
      env:
        PACKAGE_NAME: ${{ github.event.repository.name }}
      run: pipenv run python setup.py bdist_wheel
